import { AiOutlinePlusCircle } from "react-icons/ai";
import { GrNext, GrChapterNext, GrLinkPrevious } from "react-icons/gr";
import {
  MdOutlineAddLocationAlt,
  MdOutlineStarPurple500,
  MdKeyboardArrowUp,
  MdKeyboardArrowDown,
  MdMessage,
  MdPhone,
  MdOutlineHouseSiding,
  MdLocationCity,
  MdOutlinePercent,
  MdOutlineRefresh,
} from "react-icons/md";
import { FaRegMoneyBillAlt, FaSearchLocation } from "react-icons/fa";
import { FaChartArea, FaDeleteLeft } from "react-icons/fa6";
import {
  BsBuildings,
  BsChevronRight,
  BsBookmarkStarFill,
  BsCurrencyDollar,
  BsShieldCheck,
} from "react-icons/bs";
import { IoIosHeart, IoIosHeartEmpty, IoMdClose } from "react-icons/io";
import {
  HiOutlineLocationMarker,
  HiOutlineHome,
  HiOutlinePhotograph,
} from "react-icons/hi";
import { TbReportMoney } from "react-icons/tb";
import { RiCrop2Line } from "react-icons/ri";
import {
  FiSearch,
  FiEdit3,
  FiTrash2,
  FiUpload,
  FiImage,
  FiMapPin,
  FiStar,
  FiCheck,
  FiInfo,
  FiAward,
  FiShield,
  FiArrowRight,
  FiArrowLeft,
  FiMail,
  FiClock,
  FiPlus,
  FiZap
} from "react-icons/fi";
import { GiTakeMyMoney } from "react-icons/gi";
import {
  BiCategory,
  BiText,
  BiMoney,
  BiMap,
  BiCamera,
  BiCheckCircle,
  BiInfoCircle,
  BiAward,
  BiShield,
  BiSupport,
  BiRefresh,
  BiCrown,
  BiCalendar,
  BiCalculator,
  BiErrorCircle,
  BiCreditCard,
  BiImage,
  BiMapPin,
  BiLoaderAlt,
  BiClipboard,
} from "react-icons/bi";
import {
  HiSparkles,
  HiLightBulb,
  HiPhotograph,
  HiCash,
  HiCheckCircle,
  HiExclamationCircle,
  HiInformationCircle,
  HiCreditCard,
} from "react-icons/hi";
import { LuBoxes } from "react-icons/lu";
import { IoChatboxEllipsesOutline } from "react-icons/io5";
import { FaRegBell, FaHourglassHalf, FaQuestion } from "react-icons/fa";
import { TbWorld } from "react-icons/tb";
import { FaSearchengin } from "react-icons/fa6";
import { LuPackagePlus } from "react-icons/lu";
import { LuPackageSearch } from "react-icons/lu";
import { FaBalanceScale } from "react-icons/fa";
import { IoBarChart } from "react-icons/io5";
import { BsCart4 } from "react-icons/bs";
import {
  FiUser,
  FiGift,
  FiPackage,
  FiClipboard,
  FiAlertTriangle,
  FiDollarSign,
  FiSettings,
  FiTruck,
  FiLogOut,
  FiBell,
  FiCalendar,
  FiEye,
  FiLock,
  FiUnlock,
  FiX,
  FiPause,
  FiCreditCard,
  FiRefreshCcw,
  FiFile,
  FiHome,
  FiCamera,
  FiZoomIn,
  FiPhone,
  FiFilter,
  FiDatabase, FiGlobe,FiSun, FiMoon, FiMonitor
} from "react-icons/fi";

const icons = {
  FiDatabase, FiGlobe,FiSun, FiMoon, FiMonitor,
  FiBell,
  FiFilter,
  FiCalendar,
  FiEye,
  FiLock,
  FiUnlock,
  FiX,
  FiPause,
  BiClipboard,
  FaSearchengin,
  FaHourglassHalf,
  BsCart4,
  FaBalanceScale,
  IoBarChart,
  LuPackagePlus,
  FaQuestion,
  LuPackageSearch,
  TbWorld,
  FiUser,
  FiFile,
  FiGift,
  FiPackage,
  FiClipboard,
  FiAlertTriangle,
  FiDollarSign,
  FiSettings,
  FiTruck,
  FiLogOut,
  AiOutlinePlusCircle,
  IoMdClose,
  GrNext,
  MdOutlineAddLocationAlt,
  FaRegMoneyBillAlt,
  FaChartArea,
  FaDeleteLeft,
  BsBuildings,
  FaSearchLocation,
  MdOutlineStarPurple500,
  MdOutlineRefresh,
  IoIosHeart,
  BsBookmarkStarFill,
  MdKeyboardArrowUp,
  MdKeyboardArrowDown,
  IoIosHeartEmpty,
  GrChapterNext,
  GrLinkPrevious,
  BsChevronRight,
  GiTakeMyMoney,
  HiOutlineLocationMarker,
  TbReportMoney,
  RiCrop2Line,
  MdOutlineHouseSiding,
  FiSearch,
  FiCreditCard,
  MdPhone,
  MdMessage,
  // New icons for create form
  FiEdit3,
  FiTrash2,
  FiUpload,
  FiImage,
  FiMapPin,
  FiStar,
  FiCheck,
  FiInfo,
  FiAward,
  FiShield,
  BiCategory,
  BiText,
  BiMoney,
  BiMap,
  BiCamera,
  BiCheckCircle,
  BiInfoCircle,
  BiAward,
  BiShield,
  BiSupport,
  BiRefresh,
  HiOutlinePhotograph,
  HiOutlineHome,
  BsCurrencyDollar,
  BsShieldCheck,
  MdLocationCity,
  MdOutlinePercent,
  HiSparkles,
  HiLightBulb,
  HiPhotograph,
  HiCash,
  HiCheckCircle,
  HiExclamationCircle,
  HiInformationCircle,
  BiCrown,
  BiCalendar,
  BiCalculator,
  BiErrorCircle,
  BiCreditCard,
  BiImage,
  BiMapPin,
  BiLoaderAlt,
  BiError: BiErrorCircle, // Alias for FormNavigation
  FiArrowRight,
  FiArrowLeft,
  HiCreditCard,
  LuBoxes,
  IoChatboxEllipsesOutline,
  FaRegBell,
  FiRefreshCcw,
  FiHome,
  FiCamera,
  FiZoomIn,
  FiPhone,
  FiMail,
  FiClock,
  FiPlus,
  FiZap
};

export default icons;
